// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTtqhat1bKpr0iV-t7MaAPulQsQur9gak',
    appId: '1:1048865733769:web:87fa18893c92af21e35a58',
    messagingSenderId: '1048865733769',
    projectId: 'ncti-schedule',
    authDomain: 'ncti-schedule.firebaseapp.com',
    storageBucket: 'ncti-schedule.firebasestorage.app',
    measurementId: 'G-CDV52D3014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpG49ManwXcHwbdOsudAf_rCj5Sij-20',
    appId: '1:1048865733769:android:6aed874ed3d0ee61e35a58',
    messagingSenderId: '1048865733769',
    projectId: 'ncti-schedule',
    storageBucket: 'ncti-schedule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAfOgeQPUIMTfI3v39vfx_pvff8GJfK0',
    appId: '1:1048865733769:ios:e9f081d8b3c7360ae35a58',
    messagingSenderId: '1048865733769',
    projectId: 'ncti-schedule',
    storageBucket: 'ncti-schedule.firebasestorage.app',
    iosBundleId: 'ru.ncti.schedule.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAfOgeQPUIMTfI3v39vfx_pvff8GJfK0',
    appId: '1:1048865733769:ios:e9f081d8b3c7360ae35a58',
    messagingSenderId: '1048865733769',
    projectId: 'ncti-schedule',
    storageBucket: 'ncti-schedule.firebasestorage.app',
    iosBundleId: 'ru.ncti.schedule.client',
  );
}
